name: baidu_map
description: Flutter 百度地图，目前还处在开发中，仅支持 Android
version: 0.0.2+1
author: 7c00 <i@7c00.cc>
homepage: https://github.com/qiuxiang/flutter-baidu-map
repository: https://github.com/qiuxiang/flutter-baidu-map

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: qiuxiang.flutter.baidu_map
        pluginClass: BaiduMapPlugin
      ios:
        pluginClass: BaiduMapPlugin
